### ISSUE TITLE
yaml import error & no images created

### ISSUE THREAD

**Issue by ninafiona** [nihalsoans91/Bag_to_Depth#4]
I get the following error:
```
Traceback (most recent call last):
  File "../../grabdepth.py", line 3, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
ImportError: No module named yaml
```
even though I have pyyaml installed: 
```
pip install pyyaml
Requirement already satisfied: pyyaml in ...
```
The script executes till the end though and prints `Done.`, but the rgb and depth folders remain empty. 

Update: fixed the import error with `sudo apt-get install python-yaml`, but get `ImportError: No module named rospkg` now. I think this is a ROS Noetic related issue.

**Comment by HetNaik997** [comment]
I am facing a similar issue. The RGB and depth image folders are empty for me as well. Did you get any reasons or fixes for it?
